version: '3.9'

services:
  frontend:
    image: dockerowicz/chmury-frontend:localhost
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chmury-network

  backend:
    image: dockerowicz/chmury-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - chmury-network

networks:
  chmury-network:
    driver: bridge
